### ISSUE TITLE
Scrolling not worked

### ISSUE THREAD

**Issue by NoorMohammedAnik** [jaredrummler/MaterialSpinner#104]
When more items in spinner ,scrolling not working

**Comment by UdayaLakmal** [comment]
Try set height for dropdown item list.
 

>  app:ms_dropdown_height="wrap_content"
>   app:ms_dropdown_max_height="500dp"

**Comment by jaredrummler** [comment]
Should be fixed in a4c3128a947fc5a4eed4607269b7b3060fb5139e
