### ISSUE TITLE
Set scroll postion

### ISSUE THREAD

**Issue by p158276** [jaredrummler/MaterialSpinner#22]
Hi. I'd like to provide the user with the functionality to memorize what they have clicked. After clicked I will pop the selected item to the first position. And I'd like to know how to set my scroll bar to the top after user clicked.
Thanks.

**Comment by jaredrummler** [comment]
You could sort the items and reset the spinner using `setItems(List)`

To scroll back to the top position: `spinner.getListView().smoothScrollToPosition(0);`
