### ISSUE TITLE
Some rows are  hidden on the first run!

### ISSUE THREAD

**Issue by githubsrinath** [jaredrummler/MaterialSpinner#25]
My XML looks like this

```xml
        <com.jaredrummler.materialspinner.MaterialSpinner
                android:id="@+id/sp_invoice_prepared_by"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="0.46"
                android:textSize="@dimen/_15sdp" />
```

My values are set like this

```java
 String[] InvoiceTaxMethod = new String[]{"STANDARD", "NO-TAX", "SIMPLE"};
```

On the first run view is showing the with out STANDARD

![first](https://cloud.githubusercontent.com/assets/4478246/17889042/d984259e-694b-11e6-94e6-7d823c721ca3.png)

After just opening the Spinner and selecting the same value NO-TAX..  NOW STANDARD is appearing

![second](https://cloud.githubusercontent.com/assets/4478246/17889086/2e4250c4-694c-11e6-9d74-2d09497b971a.png)

Have I missing anything?  Please help?

Thanks.
Srinath Rao

**Comment by jaredrummler** [comment]
Did you fix this? Please show the code where you setup the adapter/items.

**Comment by mahasadhu** [comment]
I also experienced the exact same problem, found no fix so far

**Comment by wiseideal** [comment]
the dropdown menu is inflate with listview. try some mojo with listview

**Comment by matlinder** [comment]
What is the solution to this problem?
