### ISSUE TITLE
Unable to delete the items in the spinner control

### ISSUE THREAD

**Issue by niyasmohaideen** [jaredrummler/MaterialSpinner#29]
Hi,

I am unable to find method to remove all the items from the spinner control. I have two spinner controls and second spinner will be populated based on first spinner control option selected by user. So i have to clear all the existing items and populate with new items.

Please provide solution to remove the items from the spinner control.

**Comment by jaredrummler** [comment]
You can use `setItems`. Example:

```java
spinner.setItems(Collections.emptyList());
```
