### ISSUE TITLE
Options position problem in dialog.

### ISSUE THREAD

**Issue by khalid-mahmood** [jaredrummler/MaterialSpinner#31]
i use spinner in custom dialog. options position  align to bottom of dialog. 
![device-2017-01-03-141830](https://cloud.githubusercontent.com/assets/6528169/21603500/a5dd8744-d1bf-11e6-83e8-b191fe697b7d.png)

**Comment by adisiji** [comment]
I have this problem too. I think it caused by the dialog fragment.
![screenshot_1487858899](https://cloud.githubusercontent.com/assets/6379314/23262376/07336b1a-fa0d-11e6-86bb-323be6798244.png)

**Comment by dukerok** [comment]
Hi, my workaround overrides expand() method. I have replaced getLocationOnScreen(location) to getLocationInWindow(location). It works for me now.

**Comment by jaredrummler** [comment]
5d409eebd728c6b210bcd7f6e9707d0ad914349e should fix this.
