### ISSUE TITLE
Not working with SimpleCursorAdapter

### ISSUE THREAD

**Issue by brunomilhan** [jaredrummler/MaterialSpinner#33]
Hello, this lib not working with SimpleCursorAdapter?  :/
![image](https://cloud.githubusercontent.com/assets/8545568/22565785/97141e76-e970-11e6-9e73-7f01f7736c14.png)

![image](https://cloud.githubusercontent.com/assets/8545568/22565842/ce794bd4-e970-11e6-9c6e-e48f2291d073.png)

```
MaterialSpinner materialSpinner = (MaterialSpinner) view.findViewById(R.id.sp_edit_state);

        SqliteHelper db = new SqliteHelper(getContext());
        Cursor c = db.getStates();

        SimpleCursorAdapter adapter = new SimpleCursorAdapter(getContext(),
                android.R.layout.simple_list_item_1,
                c,
                new String[] {"name"},
                new int[] {android.R.id.text1}, 0);
        materialSpinner.setAdapter(adapter);
```

This cursor is working fine, i replace to android spinner and showed my results normaly.

**Comment by jaredrummler** [comment]
It looks like the text is white on white. This was fixed here a062680b0c9aac61af52fe29796b13cf435f0c82 and will be in the next release. I haven't tried this with `SimpleCursorAdapter` so if you still have issues after the next release please comment and I will re-open.
