### ISSUE TITLE
Rounded Corner

### ISSUE THREAD

**Issue by Rushabhs999** [jaredrummler/MaterialSpinner#35]
How to set spinner edges as rounded ?

**Comment by RikySaepuloh** [comment]
@Rushabhs999 i know it's been a while since then, but you can wrap a MaterialSpinner inside a MaterialCardView and use the MaterialCardView radius to make the MaterialSpinner have rounded corners. 

Example :

        <com.google.android.material.card.MaterialCardView

            android:layout_width="wrap_content"

            android:layout_centerVertical="true"

            android:layout_alignParentEnd="true"

            app:cardCornerRadius="15dp"

            android:layout_height="wrap_content">

            <com.jaredrummler.materialspinner.MaterialSpinner

                android:id="@+id/spinner"

                android:layout_width="wrap_content"

                app:ms_padding_top="5dp"

                app:ms_padding_left="13dp"

                app:ms_padding_right="13dp"

                app:ms_padding_bottom="5dp"

                android:textColor="@android:color/white"

                app:ms_arrow_tint="@android:color/white"

                app:ms_background_color="@color/colorPrimary"

                android:layout_height="wrap_content"/>

        </com.google.android.material.card.MaterialCardView>

Hope this helps
