### ISSUE TITLE
Unresposive and slow UI ? 

### ISSUE THREAD

**Issue by navotera** [jaredrummler/MaterialSpinner#36]
im using this library in fragment but why it make the UI become slow or unresponsive for some second ? 

**here my code :** 
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.jaredrummler.materialspinner.MaterialSpinner
        android:id="@+id/spinner"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

</android.support.constraint.ConstraintLayout>`

**and my fragment code :** 

`  @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        rootView = inflater.inflate(R.layout.d, container, false);
        this.container = container;

        MaterialSpinner spinner = (MaterialSpinner) rootView.findViewById(R.id.spinner);
        spinner.setItems("Ice Cream Sandwich", "Jelly Bean", "KitKat", "Lollipop", "Marshmallow");
        spinner.setOnItemSelectedListener(new MaterialSpinner.OnItemSelectedListener<String>() {

            @Override public void onItemSelected(MaterialSpinner view, int position, long id, String item) {
                Snackbar.make(view, "Clicked " + item, Snackbar.LENGTH_LONG).show();
            }
        });

        return rootView;
    }`

**and here the error in logcat with "No Filter" selected :** 
`03-30 08:59:49.657 1582-1753/system_process W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client 03-30 08:59:58.262 18897-18897/navotera.syasep W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed. `
thanks u

**Comment by jaredrummler** [comment]
It shouldn't. It must be something else you are doing.
