### ISSUE TITLE
How to change item text size?

### ISSUE THREAD

**Issue by ChillingVan** [jaredrummler/MaterialSpinner#40]
I see the item TextView is at ms__list_item.xml. And I do not find out where to set the item. Of course, I can set a new adapter to do this.  But maybe a convenient method is better.
Thanks.

**Comment by jaredrummler** [comment]
Sorry for the delayed reply. I won't be adding a convenience method for this. Pull requests are welcome. You can use your own `MaterialSpinnerAdapter` and override `getView` to customize the dropdown. Thanks.
