### ISSUE TITLE
Why in the dialog will appear this kind of circumstance?

### ISSUE THREAD

**Issue by ZhangLanqiu** [jaredrummler/MaterialSpinner#47]
![qq 20170821151954](https://user-images.githubusercontent.com/23022347/29507788-3a153b86-8684-11e7-9731-0c92a99da55f.png)

### Why in the dialog will appear this kind of circumstance?

**Comment by jaredrummler** [comment]
It shouldn't be used in a dialog because it uses a PopupWindow.
