### ISSUE TITLE
Avoid spinner wrapping text

### ISSUE THREAD

**Issue by TobiPristupin** [jaredrummler/MaterialSpinner#49]
Hello, I really like your library, I just have a small issue with it. How can I avoid the spinner drop-down wrapping text and putting ellipses when there's plenty of space?

**Comment by jaredrummler** [comment]
Will you please provide a screenshot. I will re-open the issue when more details are provided. Thanks.

**Comment by TobiPristupin** [comment]
First of all thanks for the library I really liked it!

My question is the following:

In this image when selecting "All" two options are cut
![screenshot_20170930-114645](https://user-images.githubusercontent.com/22137035/31047301-ea45314e-a5bc-11e7-8bf0-6e5f76aeeeac.png)

When selecting "Month" no options are cut
![screenshot_20170930-114653](https://user-images.githubusercontent.com/22137035/31047309-0452c376-a5bd-11e7-83cb-77ba8a703b20.png)

When selecting "Week" no options are cut, and when selecting "Year" only "Month" option is cut.

Is the shrinking a feature or a bug? If it is a feature then it is inconsistent, it seems to not follow any formatting rules. When selecting "Week" a 4 character word no options are cut, but when selecting "Year", also four characters it cuts one of the options.

Is there any way to disable it?


Thanks for supporting the library 👍

**Comment by jaredrummler** [comment]
This will be fixed in 1.2.1. You can also specify the layout_height instead of setting wrap_content.

**Comment by TobiPristupin** [comment]
Updated to 1.2.1 and issue was fixed.
