### ISSUE TITLE
Accessing Adapter for notify data changed

### ISSUE THREAD

**Issue by MoustafaElsaghier** [jaredrummler/MaterialSpinner#50]
When I was using this awesome lib I couldn't update the data in runtime 
I could only by using setItems and I needed to remove item and update the list for next use but I couldn't do this 
Please provide us notify data change that I can found in the adapter

**Comment by jaredrummler** [comment]
I haven't worked on this project in awhile but trying to cleanup the issues here.

You can provide your own adapter to the spinner. Example:

```java
MaterialSpinner spinner = (MaterialSpinner) findViewById(R.id.spinner);

final List<String> items = new ArrayList<>();
items.add("Foo");
items.add("Bar");

final MaterialSpinnerAdapter<String> adapter = new MaterialSpinnerAdapter<>(this, items);

spinner.setAdapter(adapter);
spinner.setItems(items);

// add items to the spinner after 3 seconds
new Handler().postDelayed(new Runnable() {
  @Override public void run() {
    items.add("Baz");
    items.add("Qux");
    adapter.notifyDataSetChanged();
  }
}, 3000);
```

One issue is that you need to call `setItems` too. This shouldn't be necessary and something I should change.

Does this resolve your issue?
