### ISSUE TITLE
How to delete or clear the spinner 

### ISSUE THREAD

**Issue by azaabudeen** [jaredrummler/MaterialSpinner#54]
I want to update the spinner when the user selects something, but the previous values are also there. I want to delete them. How can I clear the spinner?

**Comment by jaredrummler** [comment]
You can set the `MaterialSpinner.OnItemSelectedListener` to the spinner and then set the items in `onItemSelected`. If that doesn't work, please post some code and add more details of what you are attempting to accomplish.
