### ISSUE TITLE
Need help in getting selected item and display it as string

### ISSUE THREAD

**Issue by svetaz** [jaredrummler/MaterialSpinner#63]
Hello,can you please help me,i am trying to get selected item from your spinner and display it as string,i tried standard spinnerABC.getSelectedItem().toString() but its not working :/
Thanks in advance.

Btw,superb view,thumbs up 👍 👍 👍

**Comment by jaredrummler** [comment]
You can use either:

```java
String selectedText = spinner.getText().toString();
```

or

```java
spinner.getItems().get(spinner.getSelectedIndex());
```

**Comment by svetaz** [comment]
Thanks,works like charm 👍 
I also tried to performClick() on it,but cant get it to work with standard android spinner method:
`((MaterialSpinner) findViewById(R.id.spinner)).performClick();`
Any tip on that?

Thanks again for your help and for this superb looking view!

**Comment by jaredrummler** [comment]
You can use `spinner.expand()`
