### ISSUE TITLE
Spinner with only one item

### ISSUE THREAD

**Issue by burgab** [jaredrummler/MaterialSpinner#68]
When adding a list with a single item, the spinner does't show that item. For two or more items everything it is ok.

**Comment by castrojr913** [comment]
@jaredrummler It doesn't work. Do you have a example?

**Comment by clj0020** [comment]
@jaredrummler Still does not work. Adding items from my array resource file like

```
val adapter = ArrayAdapter.createFromResource(context,
                                R.array.example_array, android.R.layout.simple_spinner_item)
adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
spinner.setAdapter(adapter)
```
But one of my arrays has only one item and it does not fill the spinner with any values.
