### ISSUE TITLE
how to set different background image for spinner and dropdown item

### ISSUE THREAD

**Issue by feidi2014** [jaredrummler/MaterialSpinner#69]
ms_background_selector sets for both, I need to set background image for spinner only not dropdown items

**Comment by jaredrummler** [comment]
I should add support for this. For now you could do:

```java
spinner.getPopupWindow().getBackground().setColorFilter(Color.WHITE, PorterDuff.Mode.SRC_IN);
```

or

```java
spinner.getPopupWindow().setBackgroundDrawable(ContextCompat.getDrawable(context, R.drawable.ms__drawable));
```

**Comment by feidi2014** [comment]
@jaredrummler what I need is to set image for spinner and color for drop down item

**Comment by feidi2014** [comment]
![screen shot 2017-12-08 at 4 36 47 pm](https://user-images.githubusercontent.com/19205514/33757690-31110a26-dc36-11e7-8592-281a1455ef57.png)

as you can see, I set ms_background_selector as well as spinner.getPopupWindow().setBackgroundDrawable but no luck
I need to know the way how to remove background image for each drop down item

**Comment by feidi2014** [comment]
I ended up with android:background instead of ms_background_selector
