### ISSUE TITLE
Use Android 7.0

### ISSUE THREAD

**Issue by liuzy1993** [jaredrummler/MaterialSpinner#70]
If my data is particularly large, the interface will fill the height of the entire screen

**Comment by jaredrummler** [comment]
Use `ms_dropdown_max_height`. Example in demo:

```xml
  <com.jaredrummler.materialspinner.MaterialSpinner
      android:id="@+id/spinner"
      app:ms_dropdown_max_height="350dp"
      app:ms_dropdown_height="wrap_content"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"/>
```

https://github.com/jaredrummler/MaterialSpinner/blob/master/demo/src/main/res/layout/content_main.xml

**Comment by liuzy1993** [comment]
Thank you for your answer, I have according to your settings, I set the height of the spinner, setPadding, but the problem persists.
 dataBinding.drugsFluidsWoundDrug.setPadding(10,0,10,0);
 <com.jaredrummler.materialspinner.MaterialSpinner
                    android:id="@+id/drugs_fluids_wound_drug"
                    android:layout_width="match_parent"
                    android:layout_height="30dp"
                    app:ms_dropdown_height="wrap_content"
                    app:ms_dropdown_max_height="350dp"/>

**Comment by liuzy1993** [comment]
If I'm fixed data,
       app: ms_dropdown_max_height = "350dp"
       app: ms_dropdown_height = "wrap_content"
 is useful, 
but if I'm data from a web request it will not work, showing full screen

**Comment by liuzy1993** [comment]
Thanks for your answer, I found that adding the
       app: ms_dropdown_max_height = "350dp"
       app: ms_dropdown_height = "wrap_content" 
If it is fixed data will be successful, if the network requests a large amount of data does not succeed, you need to add setDropdownMaxHeight after setItems, I have been resolved.
