### ISSUE TITLE
how to set different color for selected value?

### ISSUE THREAD

**Issue by feidi2014** [jaredrummler/MaterialSpinner#73]
is it possible to get this done using setTextColor?

**Comment by jaredrummler** [comment]
I should add support for this. Here is a little bit of a hacky way to get it done:

```java
MaterialSpinnerAdapter adapter = (MaterialSpinnerAdapter) spinner.getListView().getAdapter();
spinner.setTextColor(Color.BLUE);
adapter.setTextColor(Color.GREEN);
```

This would set the selected text to blue and the items to green.

**Comment by feidi2014** [comment]
thanks it works!
