### ISSUE TITLE
Part of the content is not display !

### ISSUE THREAD

**Issue by xuhongv** [jaredrummler/MaterialSpinner#74]
hello , now I have 16 Items to display ,but this only display 13 Item ,this my screenshot.

![device-2017-12-30-100859](https://user-images.githubusercontent.com/25237870/34450665-743aa954-ed4a-11e7-9512-3ac56b467a1a.png)

**Comment by mayur-novus** [comment]
@xuhongv You will need to set a fixed max height for your dropdown list.
Example:  `app:ms_dropdown_max_height="350dp"`

This worked for me with 100 items in dropdown
