### ISSUE TITLE
Hi how can i use the material spinner in and Recylerview Adaper ??

### ISSUE THREAD

**Issue by frankyxcs** [jaredrummler/MaterialSpinner#77]
Hi I can youse a normal spinner in an recylerview like this to get the adaper position of the selected item like this 

<code>
    holder.spinner.setOnItemSelectedListener(new
     AdapterView.OnItemSelectedListener() {
   @Override
   public void onItemSelected(AdapterView<?> parent, View view, int
               position, long id) {
              // On selecting a spinner item

            String item = parent.getItemAtPosition(position).toString();

       }

    @Override
     public void onNothingSelected(AdapterView<?> parent) {
       // todo for nothing selected
      }
     });

</code>

Can i make the same with this material spinner ??? Any solution would be nice . Thanx in advance

**Comment by jaredrummler** [comment]
Set on `OnItemSelectedListener` on the spinner:

```java
spinner.setOnItemSelectedListener(new MaterialSpinner.OnItemSelectedListener<String>() {

  @Override public void onItemSelected(MaterialSpinner view, int position, long id, String item) {
    
  }
});
```
