### ISSUE TITLE
First item is not shown when added app:ms_hint attribute

### ISSUE THREAD

**Issue by Lmpgdn** [jaredrummler/MaterialSpinner#80]
I have 5 items on my list but only the last 4 items are shown on the spinner.

This is my code from my xml file:
```
<com.jaredrummler.materialspinner.MaterialSpinner
            android:id="@+id/spinner_home_team"
            android:layout_width="125dp"
            android:layout_height="wrap_content"
            app:ms_hint="@string/spinner_hint_select_team"
            app:ms_hint_color="@color/gray"
            app:ms_text_color="@color/colorPrimary"
            app:ms_dropdown_max_height="200dp"/>
```

The issue happens when I added a hint to `app:ms_hint` attribute. The first item is not always shown.
However, if I select an item from the spinner, then I can see the first item on the list.

I think it only happens when the hint text is shown in the spinner.

With hint:
<img src="https://user-images.githubusercontent.com/20717836/35795754-1fad4a78-0a95-11e8-976e-37ec5717b6b0.jpg" width="25%" />

Without hint:
<img src="https://user-images.githubusercontent.com/20717836/35795655-c8d97564-0a94-11e8-9624-efb408717448.jpg" width="25%" />

**Comment by Teless** [comment]
I'm having the same error, for now I resolved that by creating a custom Adapter that don't hide the selected item, instead of setting the itens I'm setting the adapter. Let's see if there is a better solution, I like the feature of hiding the selected value

```
public class CustomMaterialSpinnerAdapter<T> extends MaterialSpinnerAdapter<T> {

    public CustomMaterialSpinnerAdapter(Context context, List<T> items) {
        super(context, items);
    }

    @Override public T getItem(int position) {
        return getItems().get(position);
    }
}
```

**Comment by mob-rockstar** [comment]
I have same issue in my app.

**Comment by Hamdy-khader** [comment]
Hi,
I fixed the issue and waiting for merge, meanwhile you can use my fix from here:
https://github.com/jaredrummler/MaterialSpinner/tree/a514f4d7f48156c9f384bf0e844afb59d1218992

**Comment by mob-rockstar** [comment]
so currently Spinner is working well without issue I posted?

**Comment by Hamdy-khader** [comment]
if you didn't use the hint attribute then yes.

**Comment by mob-rockstar** [comment]
I should use the hint text in spinner

**Comment by Hamdy-khader** [comment]
well, you can clone my fix or wait for my pull request to me merged.

**Comment by mob-rockstar** [comment]
what is your fix in MaterialSpinner
can you share in detail?

**Comment by Hamdy-khader** [comment]
download this version of the library as a zip and import it as a module in your android studio.
https://github.com/jaredrummler/MaterialSpinner/tree/a514f4d7f48156c9f384bf0e844afb59d1218992

**Comment by mob-rockstar** [comment]
ok, I will try.

**Comment by mob-rockstar** [comment]
so are you sure in this version spinner works well even if I set the spinner hint?

**Comment by Hamdy-khader** [comment]
yep :)
![screenshot_1521667325](https://user-images.githubusercontent.com/7796851/37738123-b159c320-2d5e-11e8-999e-1b222a18704f.png)

**Comment by mob-rockstar** [comment]
Ok, good

**Comment by zaen323** [comment]
Wow I'm surprised that this was 2 days ago!
Thanks a lot for fixing it.
