### ISSUE TITLE
how to make searchable

### ISSUE THREAD

**Issue by Avinash4201** [jaredrummler/MaterialSpinner#81]
not able to search item.how to ssearch an item

**Comment by jaredrummler** [comment]
Please elaborate. You can get a list of items via `spinner.getItems()`. I will re-open if there is an issue.

**Comment by Avinash4201** [comment]
There is no option in material option search item which is available on the
dropdown so please implement it as searchable also

**Comment by jaredrummler** [comment]
I still don't understand what you are referring to, sorry.
