### ISSUE TITLE
Strange behavior with two items 

### ISSUE THREAD

**Issue by isinkler** [jaredrummler/MaterialSpinner#82]
Can't select the second item if there are only two items in the ArrayAdapter.

**Comment by KevinGaitan** [comment]
i have the same problem

**Comment by nkarasch** [comment]
#101 I had the same problem, this worked for my use case. `implementation 'com.github.nkarasch:MaterialSpinner:master-SNAPSHOT'`

**Comment by ITbody** [comment]
i too have same problem, leme know how you fixed ? @isinkler

**Comment by isinkler** [comment]
I started to use the default spinner with custom style. @ITbody

**Comment by jaredrummler** [comment]
Fixed f5ae6af4c8d58b4a40de8c5b11c24d9c36c7cd11
