### ISSUE TITLE
Background transparent problem

### ISSUE THREAD

**Issue by aolmez** [jaredrummler/MaterialSpinner#83]
there 3 spinner in my activity and two spinner show items in white backsground but one spinner show items in transparent background. i make only set data source not another process. Can you help me ?

**transparent background**
 <com.jaredrummler.materialspinner.MaterialSpinner
                    android:id="@+id/ilSpinner"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="10dp"
                    android:hint="@string/txtIl" />
 **white background**
  <com.jaredrummler.materialspinner.MaterialSpinner
                    android:id="@+id/ilceSpinner"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="10dp"
                    android:hint="@string/txtIlce" />

**Comment by Ferrmolina** [comment]
Same problem with 2 spinners in an activity with `Theme.AppCompat.Light.Dialog` theme.
![image](https://user-images.githubusercontent.com/1312328/36923970-b5e4dd84-1e4b-11e8-99c9-14e2a96e82ee.png)
![image](https://user-images.githubusercontent.com/1312328/36923978-baf11310-1e4b-11e8-8bb2-508dc1f30fd8.png)
![image](https://user-images.githubusercontent.com/1312328/36923986-befcc210-1e4b-11e8-89c3-e63e55790d89.png)

**Comment by jaredrummler** [comment]
Can't reproduce this. Will close for now.

**Comment by bmbariah** [comment]
Same problem on Android 6.0, Android 9 seem be ok.
