### ISSUE TITLE
Path too large to be rendered into a texture

### ISSUE THREAD

**Issue by ibolat38** [jaredrummler/MaterialSpinner#85]
Im getting 'W/OpenGLRenderer: Path too large to be rendered into a texture' this error. What's reason ? @jaredrummler 

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:weightSum="1"
                        android:layout_margin="5dp"
                        android:orientation="horizontal">

                        <com.jaredrummler.materialspinner.MaterialSpinner
                            android:id="@+id/spinnerGelisHavaalani"
                            android:layout_width="match_parent"
                            android:layout_weight="0.5"
                            android:layout_height="wrap_content"/>

                        <com.jaredrummler.materialspinner.MaterialSpinner
                            android:id="@+id/spinnerDonusHavaalani"
                            android:layout_width="match_parent"
                            android:layout_weight="0.5"
                            android:layout_height="wrap_content"/>

                    </LinearLayout>

**Comment by ibolat38** [comment]
@jaredrummler

**Comment by proishere** [comment]
I think if you add a max height of some value, then this message should go away. Example:
`app:ms_dropdown_max_height="350dp"`

**Comment by jaredrummler** [comment]
Please post stacktrace. It doesn't look like this is related to `MaterialSpinner`. Because this is so old (sorry for the delayed reply) I will close this for now, but will re-open with more details. Thanks.
