### ISSUE TITLE
second time setItems on activity, spinner list displaying window height not changed

### ISSUE THREAD

**Issue by bewithdhanu** [jaredrummler/MaterialSpinner#87]
List<String> list = new ArrayList<>();
        list.add("-select-");
        vehicleSpinner.setItems(list);

after some calls am again setting items for spinner
ArrayList<String> list = new ArrayList<>();
list.add("-select-");
for (int i = 0; i < loadList.size(); i++) {
        list.add(loadList.get(i).getLoadId() + " - " + loadList.get(i).getFrom() + " - " + loadList.get(i).getTo());
}
loadSpinner.setItems(list);
second-time setItems on activity, spinner list displaying window height not changed

**Comment by jaredrummler** [comment]
Fixed 106c260dd83e6f11bf5de19f0ee60eb6f4faed35
