### ISSUE TITLE
Can't be shown completely when using in a AlertDialog

### ISSUE THREAD

**Issue by TimeWatcher** [jaredrummler/MaterialSpinner#90]
If the spinner is used like this, some parts of it will be cut, which will make some options unselectable.

AlertDialog.Builder builder = new AlertDialog.Builder(this) 
// some code...
MaterialSpinner spinner = new MaterialSpinner(this);
// some code...
builder.setView(spinner);
builder.show()

If the height of dialog is shorter than the spinner, it will be cut and can't be displayed completely.

**Comment by vomobile** [comment]
I have the same problem, if anyone knows how to fix it, please, help us!

**Comment by iamriajul** [comment]
Is there anyone who can fix this and help us! please!

**Comment by BestAndroidProgrammer** [comment]
can someone find answer?

**Comment by jaredrummler** [comment]
Related StackOverflow question: https://stackoverflow.com/questions/41020609/popupwindow-inside-dialog

I will not be fixing this as I don't think it is possible since it uses a `PopupWindow`.
