### ISSUE TITLE
setItems()

### ISSUE THREAD

**Issue by burgab** [jaredrummler/MaterialSpinner#96]
Hello!
I have something like this:

```
myList = ...........some list;
spinner.setItems(myList);
```

```
myList = ......... a new some list;
spinner.setItems(myList);
```

When I set the second time it seems that does not reinitialize again.
 Is there any way to reinitialize the view so I can reuse the spinner view?

**Comment by nalancer08** [comment]
Can you solved the issue?

**Comment by jaredrummler** [comment]
106c260dd83e6f11bf5de19f0ee60eb6f4faed35 should fix this
