### ISSUE TITLE
setTextColor() doesn't set the color to spinner items.

### ISSUE THREAD

**Issue by Andy671** [jaredrummler/MaterialSpinner#97]
Hello. 
setTextColor() method works only before items are assigned. 

So, when I want to change spinner with the inflated list of items - I can't. It just changes the color of main spinner item. 

Currently, I solve this by resetting the item list. 

Please, take a look at this issue.

**Comment by ArigarasuthanRepo** [comment]
use   **app:ms_text_color** property to set text color.

**Comment by Andy671** [comment]
I needed to change colors dynamically. I used something else at that time when I needed it.

**Comment by serhii-pokrovskyi** [comment]
i can confirm. This is very annoying bug
